### ISSUE TITLE
Can't find any tests

### ISSUE THREAD

**Issue by thlorenz** [CondeNast/JSXHint#2]
I looked around, but couldn't see where you ensure that this module actually works.
Also the `travis.ci` icon doesn't seem to be displayed anywhere where I can see it.

I mean you don't expect me to just trust you and spend my time pulling this down to possibly find out that this doesn't work at all?

Could you please point me to where the tests are hiding and/or implement them and add travis.ci.

Thanks.

**Comment by toddself** [comment]
There are no tests right now. Hence why this is 0.1.0. 

When it has tests it'll be 1.0.0.

If you don't trust me, don't use it!
